### ISSUE TITLE
Add examples to the paper

### ISSUE THREAD

**Issue by andrewmkeller** [byuccl/scipy_proceedings#2]
This addresses comments from both reviewers:

* Would it be possible to include some snippets of SpyDrNet in use, just to kind of show off the API perhaps? For example, it would help with both conceptual and use case understanding for the reader to be able to include short excerpts of concrete code to demonstrate the workflow; even if it's just copied from the repo README

* In each of the subsections, you could envision appending a code snippet to kind of bring all the ideas discussed in the section together in a pragmatic way—here's the abstraction, and here's the code.

* I would love to see examples. Especially in the section where the author talks about utility functions - it would be good to show how those features (API, hierarchy etc) - provide ease, power and flexibility to hardware engineers/end-users in their workflow.

**Comment by thunder-hammer** [comment]
5cc4215c9dbd503f45b9d4e61afa44c6d3f3e734 addresses this issue
