### ISSUE TITLE
Update figure on IR structure

### ISSUE THREAD

**Issue by andrewmkeller** [byuccl/scipy_proceedings#7]
https://www.rapidwright.io/docs/RapidWright_Overview.html#edif-package-logical-netlist similar to this maybe?

**Comment by andrewmkeller** [comment]
Lower priority than other issues. Need to point out the outerPin innerPin issue (most trick part of the data structure).

**Comment by thunder-hammer** [comment]
It is looking more and more like I will not get to this today.

**Comment by andrewmkeller** [comment]
Save for documentation update
