### ISSUE TITLE
Change the presentation of components in the IR

### ISSUE THREAD

**Issue by andrewmkeller** [byuccl/scipy_proceedings#9]
Either add bold or underline to the component name in the subsubsection or restructure in a way that higlights these elements better.

**Comment by andrewmkeller** [comment]
Could we have the IR representation figure appear closer to the description of elements.

**Comment by andrewmkeller** [comment]
From Dr. Writhlin's feedback:

> Can you talk about the data structure implementation a bit? Did you focus on quick access of data or data structure size?

**Comment by thunder-hammer** [comment]
Currently the ir representation figure appears just before the description (and the red one is just after).
e38525fdb365ba33d6bd488b272ab67be587a873
represents the changes to implement these suggestions
